"""create business/symptom tables

Revision ID: 864dc315f3b8
Revises: 
Create Date: 2025-04-21 00:33:51.129999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864dc315f3b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptoms',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('business_symptoms',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('symptom_code', sa.String(length=20), nullable=False),
    sa.Column('diagnostic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['symptom_code'], ['symptoms.code'], ),
    sa.PrimaryKeyConstraint('business_id', 'symptom_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_symptoms')
    op.drop_table('symptoms')
    op.drop_table('businesses')
    # ### end Alembic commands ###
